/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardSlugRouteImport } from './routes/$boardSlug'

const BoardSlugRoute = BoardSlugRouteImport.update({
  id: '/$boardSlug',
  path: '/$boardSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$boardSlug': typeof BoardSlugRoute
}
export interface FileRoutesByTo {
  '/$boardSlug': typeof BoardSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$boardSlug': typeof BoardSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$boardSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/$boardSlug'
  id: '__root__' | '/$boardSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BoardSlugRoute: typeof BoardSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$boardSlug': {
      id: '/$boardSlug'
      path: '/$boardSlug'
      fullPath: '/$boardSlug'
      preLoaderRoute: typeof BoardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BoardSlugRoute: BoardSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
